### ISSUE TITLE
todo まとめ

### ISSUE THREAD

**Issue by Kota-Oshiro** [Kota-Oshiro/PostMatch#3]
グロース
- [x] 日本代表用のポスト対応
- [x] CL対応
- [x] Jリーグ対応

新機能
- [ ] 観戦レポート機能
- [ ] #4
- [ ] 投稿の編集・削除機能
- [x] マッチページに、スコア情報、カード情報を入れる
- [ ] マッチページにスカッド情報を入れる
- [ ] マッチのスカッドを採点できる機能
- [x] スケジュールがuseeffectになっているのでusequeryにしたい
- [x] 最近行われた試合結果の非表示機能（切り替えボタン付き）
- [x] 順位表（順位表）
- [ ] X垢を登録しているユーザーに投稿後にシェアを促すポップアップを出す

改善
- [x] post detail や article にシェア導線を設置
- [x] postの行間もうちょい広く
- [x] スケジュールで試合中が分かるUI
- [x] アストン・ヴィラのエンブレム変更
- [ ] postで表示した後にアコーディオン処理がかかってる気がする
- [x] APIデータのmatch.statusが終了後にtimedになっている件の対応検討
- [x] postページではアコーディオンしない

考慮漏れ・バグ修正
- [x] スケジュールでハーフタイム中に試合中（点滅無し）になってるので多分ステータスが違うはず。要修正

新シーズン前にやること
- [ ] 順位表のseason_id切替（今はcompetition_idだけで取得しているから要変更対応）
